service: rsvp-api

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getGuests:
    handler: api/get-guests.getGuests
    events:
        - http:
            path: rsvp/api/guests
            method: get
            cors: true
  patchGuests:
    handler: api/patch-guests.patchGuests
    events:
        - http:
            path: rsvp/api/guests
            method: patch
            cors: true

package:
  exclude:
    - ./**
  include:
    - api/**
    - data-loaders/**
    - rsvp-logic/**
    - ss-config.json
    - node_modules/**
